#!/usr/bin/env bash

set -euo pipefail

# because the environment hook runs in ./hooks/environment, we
# want to ensure that we are building a directory up

d=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
build_dir="$(dirname "$d")"

echo "~~~ :electric_plug: Building plugin hooks"
docker run --rm -v "${build_dir}":/plugin -w /plugin golang:latest go build -o hooks/pre-exit
